#!/usr/bin/env python3
"""
Run this script whenever you add or update an SVG icon:
  python3 generate-icons.sh

It reads every .svg file in assets/icons/ and writes
js/icon-data.js with all icon content embedded inline.
"""

import os, re, json

ICONS_DIR  = os.path.join(os.path.dirname(__file__), 'assets', 'icons')
OUTPUT     = os.path.join(os.path.dirname(__file__), 'js', 'icon-data.js')

def clean_svg(content):
    content = re.sub(r'<\?xml[^?]*\?>', '', content)
    content = re.sub(r'<sodipodi:namedview[\s\S]*?</sodipodi:namedview>', '', content)
    content = re.sub(r'<inkscape:[^/]*/>', '', content)
    content = re.sub(r'<!--[\s\S]*?-->', '', content)
    content = re.sub(r'\s+xmlns:(inkscape|sodipodi|dc|cc|rdf|xlink)="[^"]*"', '', content)
    content = re.sub(r'\s+(inkscape|sodipodi):[a-zA-Z-]+=(?:"[^"]*"|\'[^\']*\')', '', content)
    return content.strip()

lines = [
    '// Auto-generated by generate-icons.sh — do not edit manually.',
    '// Re-run the script after adding or changing any SVG in assets/icons/.',
    'const ICON_SVG = {',
]

icons = sorted(f[:-4] for f in os.listdir(ICONS_DIR) if f.endswith('.svg'))
for name in icons:
    with open(os.path.join(ICONS_DIR, name + '.svg'), 'r', encoding='utf-8') as f:
        svg = clean_svg(f.read())
    escaped = svg.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    lines.append(f'  {json.dumps(name)}: `{escaped}`,')

lines.append('};')

with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Written {len(icons)} icons to js/icon-data.js")
for name in icons:
    size = os.path.getsize(os.path.join(ICONS_DIR, name + '.svg'))
    print(f"  {name}.svg  ({size:,} bytes)")
